Setono\SyliusPickupPointPlugin\Model\PickupPoint:
    exclusion_policy: ALL
    xml_root_name: setono_sylius_pickup_point
    properties:
        name:
            type: string
            groups: [Detailed, Autocomplete]
        latitude:
            type: string
            groups: [Detailed, Autocomplete]
        longitude:
            type: string
            groups: [Detailed, Autocomplete]        
        distance:
            type: integer
            groups: [Detailed, Autocomplete]
    virtual_properties:
        getCode:
            serialized_name: code
            type: string
            groups: [Detailed, Autocomplete]         
        getCodeDelimiter:
            serialized_name: code_delimiter
            type: string
            groups: [Detailed, Autocomplete]            
        getDistanceKm:
            serialized_name: distance_km
            type: float
            groups: [Detailed, Autocomplete]        
        getFullAddress:
            serialized_name: full_address
            type: string
            groups: [Detailed, Autocomplete]        
        getOpeningHours:
            serialized_name: opening_hours
            groups: [Detailed, Autocomplete]
